server:
  port: ${SERVER_PORT||8080}

auth:
  jwksUrl: https://auth.mlevsh.in/realms/project-base/protocol/openid-connect/certs
  audience: my-finance-backend

db:
  dsn: "host=localhost user=postgres password=postgres dbname=postgres port=5432 sslmode=disable"